# Generated by Django 5.2.7 on 2025-10-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_down', models.FloatField(default=0.05)),
                ('logo_position', models.CharField(max_length=50)),
                ('logo_image', models.ImageField(upload_to='logos/')),
            ],
        ),
    ]
